Repository YAPP-Github/25th-Web-Team-2-FE, pull requests merged in 2025-07, with the labels that each got.

#190 [YS-482] ToastProvider를 구현하여 함수 호출로 토스트를 띄울 수 있도록 개선
  src/app/join/components/EmailToast/EmailToast.tsx
  src/app/join/desktop/Researcher/JoinEmailStep/UnivAuthInput/AuthCodeInput/AuthCodeInput.tsx
  src/app/join/desktop/Researcher/JoinEmailStep/UnivAuthInput/UnivAuthInput.test.tsx
  src/app/join/desktop/Researcher/JoinEmailStep/UnivAuthInput/UnivAuthInput.tsx
  src/app/join/mobile/Researcher/UnivEmailInputContainer/UnivEmailInputContainer.tsx
  src/app/login/components/LoginError/LoginError.tsx
  src/app/user/profile/components/ParticipantUserInfo/ParticipantUserInfo.tsx
  src/app/user/profile/components/ResearcherUserInfo/ResearcherUserInfo.tsx
  src/app/user/profile/hooks/useFormParticipantUserInfo.ts
  src/app/user/profile/hooks/useFormResearcherUserInfo.tsx
  src/components/ButtonInput/ButtonInput.tsx
  src/components/ContactEmailInput/ContactEmailInput.test.tsx
  src/components/ContactEmailInput/ContactEmailInput.tsx
  src/components/Toast/Toasts.constants.ts
  src/components/Toast/Toasts.css.ts
  src/components/Toast/Toasts.tsx
  src/components/Toast/Toasts.types.ts
  src/hooks/useToast.ts
  src/providers/Providers.tsx
  src/providers/ToastProvider.tsx
Labels: refactor

#189 [YS-501] 저사양 환경에서 발생하는 입력 지연을 useTransition을 활용하여 INP 개선
  src/app/join/desktop/Researcher/JoinEmailStep/UnivAuthInput/UnivAuthInput.tsx
  src/app/join/hooks/useFunnel.tsx
  src/app/join/mobile/Researcher/UnivEmailInputContainer/UnivEmailInputContainer.tsx
  src/components/ButtonInput/ButtonInput.tsx
Labels: refactor

#192 [RELEASE] 1.2.1
  src/app/home/components/ExperimentPostContainer/ExperimentPostContainer.css.ts
  src/app/join/JoinPage.css.ts
  src/app/join/components/EmailToast/EmailToast.tsx
  src/app/join/desktop/Researcher/JoinEmailStep/UnivAuthInput/AuthCodeInput/AuthCodeInput.tsx
  src/app/join/desktop/Researcher/JoinEmailStep/UnivAuthInput/UnivAuthInput.test.tsx
  src/app/join/desktop/Researcher/JoinEmailStep/UnivAuthInput/UnivAuthInput.tsx
  src/app/join/desktop/layout.tsx
  src/app/join/hooks/useFunnel.tsx
  src/app/join/mobile/Researcher/UnivEmailInputContainer/UnivEmailInputContainer.tsx
  src/app/layout.tsx
  src/app/login/LoginPage.css.ts
  src/app/login/components/LoginError/LoginError.tsx
  src/app/login/desktop/layout.tsx
  src/app/my-posts/MyPostsPage.css.ts
  src/app/my-posts/components/MyPostsTable/MyPostsTable.css.ts
  src/app/my-posts/layout.tsx
  src/app/post/[postId]/desktop/components/ExperimentPostContainer/ExperimentPostContainer.css.ts
  src/app/post/[postId]/desktop/components/ExperimentPostDetailContent/ExperimentPostDetailContent.css.ts
  src/app/post/[postId]/desktop/components/ExperimentPostDetailContent/ExperimentPostDetailContent.tsx
  src/app/post/[postId]/desktop/components/ExperimentPostOutline/ExperimentPostOutline.css.ts
  src/app/post/[postId]/mobile/components/ExperimentPostMobileDetailContent/ExperimentPostMobileDetailContent.tsx
  src/app/post/[postId]/mobile/components/ExperimentPostMobileHeader/ExperimentPostMobileHeader.tsx
  src/app/upload/components/DescriptionSection/DescriptionSection.css.ts
  src/app/upload/components/UploadContainer/UploadContainer.css.ts
  src/app/user/leave/LeavePage.css.ts
  src/app/user/leave/layout.tsx
  src/app/user/profile/ProfilePage.css.ts
  src/app/user/profile/components/ParticipantUserInfo/ParticipantUserInfo.tsx
  src/app/user/profile/components/ResearcherUserInfo/ResearcherUserInfo.tsx
  src/app/user/profile/hooks/useFormParticipantUserInfo.ts
  src/app/user/profile/hooks/useFormResearcherUserInfo.tsx
  src/app/user/profile/layout.tsx
  src/components/ButtonInput/ButtonInput.tsx
  src/components/ContactEmailInput/ContactEmailInput.test.tsx
  src/components/ContactEmailInput/ContactEmailInput.tsx
  src/components/Footer/Footer.css.ts
  src/components/Toast/Toasts.constants.ts
  src/components/Toast/Toasts.css.ts
  src/components/Toast/Toasts.tsx
  src/components/Toast/Toasts.types.ts
  src/components/layout/DefaultLayout/DefaultLayout.css.ts
  src/components/layout/DefaultLayout/DefaultLayout.tsx
  src/components/layout/UserLayout/UserLayout.css.ts
  src/hooks/useToast.ts
  src/providers/Providers.tsx
  src/providers/ToastProvider.tsx
Labels: deploy

#200 [YS-519] 맵핑되지 않은 지역 수정
  src/app/home/home.constants.ts
  src/app/home/home.utils.test.ts
  src/app/home/home.utils.ts
  src/app/user/profile/mobile/components/MobileProfileSection/MobileProfileSection.tsx
  src/constants/filters.ts
Labels: fix

#203 [YS-521] 서버와 일치하지 않은 지역명 조정 (부산 강서구, 인천 전체, 인천 계양구)
  src/app/home/home.constants.ts
  src/constants/uploadRegion.ts
  src/types/filter.ts
Labels: fix

#207 [HOTFIX] 연구자일 경우 데스크톱 UI를 보여주도록 redirect 처리
  src/app/user/profile/mobile/page.tsx
Labels: fix

#201 [YS-517] 홈화면을 SSR로 변경하여 초기 로드 시점부터 공고 목록 노출 및 자동 필터링 UX 개선 & SEO 개선
  package.json
  src/apis/config/createBaseFetchClient.ts
  src/apis/config/fetchClient.ts
  src/apis/config/utils.ts
  src/apis/login.ts
  src/apis/post.ts
  src/apis/user.ts
  src/app/edit/[postId]/hooks/useEditExperimentPostMutation.ts
  src/app/edit/[postId]/hooks/useOriginExperimentPostQuery.ts
  src/app/home/components/ExperimentPostContainer/ExperimentPostCardListContainer/ExperimentPostCardListContainer.tsx
  src/app/home/components/ExperimentPostContainer/ExperimentPostContainer.css.ts
  src/app/home/components/ExperimentPostContainer/ExperimentPostContainer.tsx
  src/app/home/components/ExperimentPostContainer/FilterContainer/FilterContainer.tsx
  src/app/home/hooks/useExperimentPostListQuery.ts
  src/app/home/hooks/useParticipantInfoQuery.ts
  src/app/home/hooks/usePostAreaCountQuery.ts
  src/app/home/hooks/usePostRegionCountQuery.ts
  src/app/home/hooks/useResearcherInfoQuery.ts
  src/app/home/page.tsx
  src/app/join/JoinPage.css.ts
  src/app/join/components/JoinSuccessStep/JoinSuccessStep.css.ts
  src/app/join/hooks/useCheckValidEmailInfoMutation.ts
  src/app/join/hooks/useCheckValidEmailInfoQuery.ts
  src/app/join/hooks/useFunnel.tsx
  src/app/login/LoginPage.css.ts
  src/app/my-posts/hooks/useDeleteExperimentPostMutation.ts
  src/app/my-posts/hooks/useUpdateRecruitStatusMutation.ts
  src/app/post/[postId]/actions.ts
  src/app/post/[postId]/desktop/components/ExperimentPostInfo/ExperimentPostInfo.tsx
  src/app/post/[postId]/hooks/useApplyMethodQuery.ts
  src/app/post/[postId]/hooks/useExperimentDetailsQuery.ts
  src/app/upload/hooks/useManageExperimentPostForm.tsx
  src/app/user/profile/desktop/components/UserInfoHeader/UserInfoHeader.tsx
  src/app/user/profile/hooks/useCheckValidEmailQuery.ts
  src/app/user/profile/hooks/useUpdateParticipantInfoMutation.ts
  src/app/user/profile/hooks/useUpdateResearcherInfoMutation.ts
  src/app/user/profile/mobile/components/MobileUserInfoSection/MobileUserInfoSection.tsx
  src/components/Header/RightHeader/RightHeader.tsx
  src/components/Header/RightHeader/components/HeaderMenu/HeaderMenu.tsx
  src/components/layout/DefaultLayout/DefaultLayout.tsx
  src/constants/queryKey.ts
  src/lib/getQueryClient.ts
  src/providers/CustomQueryClientProvider.tsx
  src/utils/getQueryParamsString.ts
Labels: refactor

#210 [YS-530] 연락받을 이메일 로직 수정
  src/apis/login.ts
  src/apis/user.ts
  src/app/join/JoinPage.css.ts
  src/app/join/components/JoinButton/JoinButton.tsx
  src/app/join/components/JoinSuccessStep/JoinSuccessStep.css.ts
  src/app/join/desktop/Participant/JoinInfoStep/JoinInfoStep.tsx
  src/app/join/hooks/useCheckValidEmailInfoMutation.ts
  src/app/join/hooks/useCheckValidJoinEmailMutation.ts
  src/app/join/hooks/useCheckValidProfileEmailMutation.ts
  src/app/join/mobile/Participant/JoinAdditionalInfoStep/JoinAdditionalInfoStep.tsx
  src/app/user/profile/desktop/components/ParticipantUserInfo/ParticipantUserInfo.tsx
  src/app/user/profile/desktop/components/ResearcherUserInfo/ResearcherUserInfo.tsx
  src/app/user/profile/mobile/edit/[infoType]/components/ContactEmailEditForm.tsx
  src/components/ContactEmailInput/ContactEmailInput.test.tsx
  src/components/ContactEmailInput/ContactEmailInput.tsx
  src/constants/url.ts
Labels: fix
