Repository YAPP-Github/25th-Web-Team-2-FE, pull requests merged in 2025-02, with the labels that each got.

#34 [REFACTOR] zod 활용하여 회원가입 validation 적용
  src/apis/config.ts
  src/apis/login.ts
  src/app/home/components/PostContainer/PostContainer.tsx
  src/app/home/hooks/useParticipantInfoQuery.ts
  src/app/home/hooks/useResearcherInfoQuery.ts
  src/app/home/hooks/useUserInfo.ts
  src/app/home/hooks/useUserInfoQuery.ts
  src/app/join/JoinPage.constants.ts
  src/app/join/JoinPage.types.ts
  src/app/join/JoinPage.utils.ts
  src/app/join/components/JoinCheckboxContainer/JoinCheckbox/JoinCheckbox.styles.ts
  src/app/join/components/JoinCheckboxContainer/JoinCheckbox/JoinCheckbox.tsx
  src/app/join/components/JoinCheckboxContainer/JoinCheckboxContainer.styles.ts
  src/app/join/components/JoinCheckboxContainer/JoinCheckboxContainer.tsx
  src/app/join/components/JoinEmailStep/JoinEmailStep.tsx
  src/app/join/components/JoinEmailStep/UnivAuthInput/UnivAuthInput.tsx
  src/app/join/components/JoinInfoStep/JoinInfoStep.tsx
  src/app/join/components/JoinInput/JoinInput.styles.ts
  src/app/join/components/JoinInput/JoinInput.tsx
  src/app/join/components/Participant/JoinInfoStep/AreaTooltip.tsx
  src/app/join/components/Participant/JoinInfoStep/AreaTooltip/AreaTooltip.styles.ts
  src/app/join/components/Participant/JoinInfoStep/AreaTooltip/AreaTooltip.tsx
  src/app/join/components/Participant/JoinInfoStep/JoinInfoStep.tsx
  src/app/join/components/Participant/JoinInfoStep/JoinSelect/JoinSelect.styles.ts
  src/app/join/components/Participant/JoinInfoStep/JoinSelect/JoinSelect.tsx
  src/app/join/components/Participant/JoinInfoStep/RadioButtonGroupContainer/RadioButtonGroup/RadioButtonGroup.styles.ts
  src/app/join/components/Participant/JoinInfoStep/RadioButtonGroupContainer/RadioButtonGroup/RadioButtonGroup.tsx
  src/app/join/components/Participant/JoinInfoStep/RadioButtonGroupContainer/RadioButtonGroupContainer.tsx
  src/app/join/components/Participant/ParticipantForm.tsx
  src/app/join/components/Researcher/JoinEmailStep/JoinEmailStep.styles.ts
  src/app/join/components/Researcher/JoinEmailStep/JoinEmailStep.tsx
  src/app/join/components/Researcher/JoinEmailStep/UnivAuthInput/AuthCodeInput/AuthCodeInput.styles.ts
  src/app/join/components/Researcher/JoinEmailStep/UnivAuthInput/AuthCodeInput/AuthCodeInput.tsx
  src/app/join/components/Researcher/JoinEmailStep/UnivAuthInput/UnivAuthInput.styles.ts
  src/app/join/components/Researcher/JoinEmailStep/UnivAuthInput/UnivAuthInput.tsx
  src/app/join/components/Researcher/JoinInfoStep/JoinInfoStep.styles.ts
  src/app/join/components/Researcher/JoinInfoStep/JoinInfoStep.tsx
  src/app/join/components/Researcher/ResearcherForm.tsx
  src/app/join/components/Researcher/index.tsx
  src/app/join/hooks/useFunnel.tsx
  src/app/join/hooks/useServiceAgreeCheck.ts
  src/app/join/layout.tsx
  src/app/join/page.tsx
  src/app/login/google/layout.tsx
  src/app/login/naver/layout.tsx
  src/app/upload/components/AgeForm/AgeForm.tsx
  src/components/Header/Header.tsx
  src/hooks/useSessionStorage.ts
  src/mocks/http.ts
  src/schema/join/ParticipantJoinSchema.ts
  src/schema/join/ResearcherJoinSchema.ts
Labels: fix, feat, refactor

#39 [FEAT] next build 오류 해결 및 github actions CI 스크립트 작성
  .github/workflows/ci.yml
  src/app/join/components/Participant/JoinInfoStep/AreaTooltip/AreaTooltip.tsx
  src/app/join/components/Participant/JoinInfoStep/JoinInfoStep.tsx
  src/app/join/components/Participant/ParticipantForm.tsx
  src/app/join/components/Researcher/ResearcherForm.tsx
  src/app/join/hooks/useFunnel.tsx
  src/app/join/page.tsx
  src/app/post/[post_id]/components/PostInfo/PostInfo.tsx
Labels: feat

#41 [YS-251] postId 타입 변경사항 반영
  src/app/post/[post_id]/components/ExperimentDetailPostContainer/ExperimentDetailPostContainer.tsx
  src/app/post/[post_id]/components/ExperimentPostContainer/ExperimentPostContainer.tsx
  src/app/post/[post_id]/hooks/useApplyMethodQuery.ts
  src/app/post/[post_id]/hooks/useExperimentDetailsQuery.ts
  src/constants/url.ts
Labels: refactor

#43 [YS-238] 이미지 등록 및 등록된 이미지 조회 구현
  next.config.mjs
  src/app/post/[post_id]/ExperimentPostPage.utils.ts
  src/app/post/[post_id]/components/ExperimentPostDetailContent/ExperimentPostDetailContent.css.ts
  src/app/post/[post_id]/components/ExperimentPostDetailContent/ExperimentPostDetailContent.tsx
  src/app/post/[post_id]/components/ExperimentPostOutline/ExperimentPostOutline.css.ts
  src/app/upload/components/DescriptionSection/DescriptionSection.tsx
  src/app/upload/components/UploadContainer/UploadContainer.tsx
  src/app/upload/hooks/useManageExperimentPostForm.tsx
  src/app/upload/hooks/useUploadExperimentPostMutation.ts
  src/app/upload/hooks/useUploadImagesMutation.ts
  src/app/upload/upload.utils.ts
  src/components/Icon/icons/Maximize.tsx
  src/constants/url.ts
  src/schema/upload/uploadExperimentPostSchema.ts
  src/styles/a11y.css.ts
  src/styles/zIndex.ts
Labels: feat

#47 [YS-253] 작성 글 목록 조회 화면 개발 및 API 연동
  next.config.mjs
  package.json
  pnpm-lock.yaml
  src/apis/login.ts
  src/app/my-posts/MyPostsPage.css.ts
  src/app/my-posts/components/MyPostsContainer/MyPostsContainer.css.ts
  src/app/my-posts/components/MyPostsContainer/MyPostsContainer.tsx
  src/app/my-posts/components/MyPostsTable/MyPostsTable.css.ts
  src/app/my-posts/components/MyPostsTable/MyPostsTable.tsx
  src/app/my-posts/components/Pagination/Pagination.css.ts
  src/app/my-posts/components/Pagination/Pagination.tsx
  src/app/my-posts/components/Table/Table.css.ts
  src/app/my-posts/components/Table/Table.tsx
  src/app/my-posts/hooks/useMyPostsQuery.ts
  src/app/my-posts/layout.tsx
  src/app/my-posts/page.tsx
  src/app/post/[post_id]/ExperimentPostPage.utils.ts
  src/app/post/[post_id]/components/ExperimentPostOutline/ExperimentPostOutline.tsx
  src/app/upload/hooks/useManageExperimentPostForm.tsx
  src/app/upload/page.tsx
  src/components/Header/Header.css.ts
  src/components/Header/Header.tsx
  src/components/Icon/icons/MenuDots.tsx
  src/components/Icon/icons/ToggleOff.tsx
  src/components/Icon/icons/ToggleOn.tsx
  src/components/Icon/icons/index.ts
  src/constants/url.ts
  src/styles/colors.ts
Labels: feat, design

#52 [YS-274] next/images에 prod 도메인 추가
  next.config.mjs
Labels: chore

#54 [YS-258] 홈화면 실험 공고 무한스크롤 구현 (버튼 클릭으로 동작)
  src/apis/post.ts
  src/app/home/components/ExperimentPostContainer/ExperimentPostCardListContainer/ExperimentPostCardList/EmptyPostCard/EmptyPostCard.css.ts
  src/app/home/components/ExperimentPostContainer/ExperimentPostCardListContainer/ExperimentPostCardList/EmptyPostCard/EmptyPostCard.tsx
  src/app/home/components/ExperimentPostContainer/ExperimentPostCardListContainer/ExperimentPostCardList/ExperimentPost.css.ts
  src/app/home/components/ExperimentPostContainer/ExperimentPostCardListContainer/ExperimentPostCardList/ExperimentPost.tsx
  src/app/home/components/ExperimentPostContainer/ExperimentPostCardListContainer/ExperimentPostCardList/ExperimentPostCard/ExperimentPostCard.css.ts
  src/app/home/components/ExperimentPostContainer/ExperimentPostCardListContainer/ExperimentPostCardList/ExperimentPostCard/ExperimentPostCard.tsx
  src/app/home/components/ExperimentPostContainer/ExperimentPostCardListContainer/ExperimentPostCardListContainer.css.ts
  src/app/home/components/ExperimentPostContainer/ExperimentPostCardListContainer/ExperimentPostCardListContainer.tsx
  src/app/home/components/ExperimentPostContainer/ExperimentPostContainer.css.ts
  src/app/home/components/ExperimentPostContainer/ExperimentPostContainer.tsx
  src/app/home/components/ExperimentPostContainer/FilterContainer/AreaFilter/AreaFilter.css.ts
  src/app/home/components/ExperimentPostContainer/FilterContainer/AreaFilter/AreaFilter.tsx
  src/app/home/components/ExperimentPostContainer/FilterContainer/ContactTargetPopover/ContactTargetFilter.css.ts
  src/app/home/components/ExperimentPostContainer/FilterContainer/ContactTargetPopover/ContactTargetFilter.tsx
  src/app/home/components/ExperimentPostContainer/FilterContainer/FilterContainer.css.ts
  src/app/home/components/ExperimentPostContainer/FilterContainer/FilterContainer.tsx
  src/app/home/components/ExperimentPostContainer/FilterContainer/MatchTypeFilter/MatchTypeFilter.css.ts
  src/app/home/components/ExperimentPostContainer/FilterContainer/MatchTypeFilter/MatchTypeFilter.tsx
  src/app/home/components/PostCardList/PostCardList.tsx
  src/app/home/components/PostContainer/PostContainer.tsx
  src/app/home/hooks/useExperimentFilters.ts
  src/app/home/hooks/useExperimentPostListQuery.ts
  src/app/home/hooks/usePostListQuery.ts
  src/app/join/components/JoinCheckboxContainer/JoinCheckbox/JoinCheckbox.tsx
  src/app/page.tsx
Labels: feat

#64 [YS-316] 실험공고 univName -> place 변경사항 반영
  src/app/post/[post_id]/components/ExperimentPostOutline/ExperimentPostOutline.tsx
  src/app/post/[post_id]/hooks/useExperimentDetailsQuery.ts
  src/app/upload/components/OutlineSection/OutlineSection.tsx
  src/app/upload/hooks/useManageExperimentPostForm.tsx
  src/app/upload/hooks/useUploadExperimentPostMutation.ts
  src/schema/upload/uploadExperimentPostSchema.ts
Labels: refactor

#65 [YS-290] 공고 수정 구현
  src/apis/config.ts
  src/app/edit/[post_id]/components/EditExperimentPost.tsx
  src/app/edit/[post_id]/hooks/useEditExperimentPostMutation.ts
  src/app/edit/[post_id]/hooks/useOriginExperimentPostQuery.ts
  src/app/edit/[post_id]/layout.tsx
  src/app/edit/[post_id]/page.tsx
  src/app/join/page.tsx
  src/app/login/page.tsx
  src/app/my-posts/components/PostActionsPopover/PostActionsPopover.tsx
  src/app/post/[post_id]/ExperimentPostPage.utils.ts
  src/app/post/[post_id]/components/ExperimentPostDetailContent/ExperimentPostDetailContent.tsx
  src/app/post/[post_id]/components/ExperimentPostInfo/ExperimentPostInfo.tsx
  src/app/post/[post_id]/components/ExperimentPostOutline/ExperimentPostOutline.tsx
  src/app/post/[post_id]/components/ParticipationGuideModal/ParticipationGuideModal.tsx
  src/app/post/[post_id]/hooks/useExperimentDetailsQuery.ts
  src/app/upload/components/ApplyMethodSection/ApplyMethodSection.css.ts
  src/app/upload/components/ApplyMethodSection/ApplyMethodSection.tsx
  src/app/upload/components/CheckboxWithIcon/CheckboxWithIcon.css.ts
  src/app/upload/components/CheckboxWithIcon/CheckboxWithIcon.tsx
  src/app/upload/components/DatePickerForm/DatePickerForm.tsx
  src/app/upload/components/DescriptionSection/DescriptionSection.css.ts
  src/app/upload/components/DescriptionSection/DescriptionSection.tsx
  src/app/upload/components/OutlineSection/OutlineSection.css.ts
  src/app/upload/components/OutlineSection/OutlineSection.tsx
  src/app/upload/components/SelectForm/SelectForm.tsx
  src/app/upload/components/UploadContainer/UploadContainer.css.ts
  src/app/upload/components/UploadContainer/UploadContainer.tsx
  src/app/upload/hooks/useExperimentDate.ts
  src/app/upload/hooks/useExperimentDuration.ts
  src/app/upload/hooks/useManageExperimentPostForm.tsx
  src/app/upload/hooks/useMatchType.ts
  src/app/upload/hooks/useRegionSelect.ts
  src/app/upload/hooks/useUploadExperimentPostMutation.ts
  src/app/upload/hooks/useUserResearcherInfo.ts
  src/app/upload/upload.utils.ts
  src/components/Icon/icons/BangRound.tsx
  src/components/Icon/icons/ToggleOff.tsx
  src/components/Modal/AlertModal/AlertModal.css.ts
  src/components/Modal/AlertModal/AlertModal.tsx
  src/constants/queryKey.ts
  src/constants/url.ts
  src/schema/upload/uploadExperimentPostSchema.ts
  src/types/uploadExperimentPost.ts
Labels: feat, refactor

#70 [YS-339] 공고 수정 시 이미지 불러오지 못하는 문제 해결
  package.json
  pnpm-lock.yaml
  src/app/edit/[post_id]/components/EditExperimentPost.tsx
  src/app/upload/components/DescriptionSection/DescriptionSection.css.ts
  src/app/upload/components/DescriptionSection/DescriptionSection.tsx
  src/app/upload/hooks/useManageExperimentPostForm.tsx
Labels: fix

#71 [YS-291] QA 반영 및 이미지 로드 개선
  src/app/edit/[post_id]/components/EditExperimentPost.tsx
  src/app/edit/[post_id]/hooks/useOriginExperimentPostQuery.ts
  src/app/my-posts/components/MyPostsContainer/MyPostsContainer.tsx
  src/app/my-posts/components/MyPostsTable/MyPostsTable.css.ts
  src/app/my-posts/components/MyPostsTable/MyPostsTable.tsx
  src/app/my-posts/components/PostActionsPopover/PostActionsPopover.tsx
  src/app/my-posts/hooks/useMyPostsQuery.ts
  src/app/post/[post_id]/ExperimentPostPage.css.ts
  src/app/post/[post_id]/ExperimentPostPage.utils.ts
  src/app/post/[post_id]/components/ExperimentPostContainer/ExperimentPostContainer.css.ts
  src/app/post/[post_id]/components/ExperimentPostContainer/ExperimentPostContainer.tsx
  src/app/post/[post_id]/components/ExperimentPostDetailContent/ExperimentPostDetailContent.css.ts
  src/app/post/[post_id]/components/ExperimentPostDetailContent/ExperimentPostDetailContent.tsx
  src/app/post/[post_id]/components/ExperimentPostInfo/ExperimentPostInfo.css.ts
  src/app/post/[post_id]/components/ExperimentPostInfo/ExperimentPostInfo.tsx
  src/app/post/[post_id]/components/ExperimentPostOutline/ExperimentPostOutline.css.ts
  src/app/post/[post_id]/components/ExperimentPostOutline/ExperimentPostOutline.tsx
  src/app/post/[post_id]/components/ParticipationGuideModal/ParticipationGuideModal.css.ts
  src/app/post/[post_id]/components/ParticipationGuideModal/ParticipationGuideModal.tsx
  src/app/post/[post_id]/hooks/useApplyMethodQuery.ts
  src/app/upload/components/AgeForm/AgeForm.tsx
  src/app/upload/components/ApplyMethodSection/ApplyMethodSection.css.ts
  src/app/upload/components/ApplyMethodSection/ApplyMethodSection.tsx
  src/app/upload/components/CheckboxWithIcon/CheckboxWithIcon.css.ts
  src/app/upload/components/CheckboxWithIcon/CheckboxWithIcon.tsx
  src/app/upload/components/DatePickerForm/DatePickerForm.css.ts
  src/app/upload/components/DatePickerForm/DatePickerForm.tsx
  src/app/upload/components/DescriptionSection/DescriptionSection.css.ts
  src/app/upload/components/DescriptionSection/DescriptionSection.tsx
  src/app/upload/components/InputForm/InputForm.css.ts
  src/app/upload/components/InputForm/InputForm.tsx
  src/app/upload/components/OutlineSection/OutlineSection.css.ts
  src/app/upload/components/OutlineSection/OutlineSection.tsx
  src/app/upload/components/RadioButtonGroup/RadioButtonGroup.tsx
  src/app/upload/components/SelectForm/SelectForm.tsx
  src/app/upload/components/UploadContainer/UploadContainer.css.ts
  src/app/upload/components/UploadContainer/UploadContainer.tsx
  src/app/upload/hooks/useManageExperimentPostForm.tsx
  src/components/Header/Header.css.ts
  src/components/Header/Header.tsx
  src/components/Icon/icons/Alert.tsx
  src/components/Icon/icons/AlertOutlined.tsx
  src/components/Icon/icons/index.ts
  src/components/Spinner/Spinner.css.ts
  src/components/Spinner/Spinner.tsx
  src/constants/queryKey.ts
  src/schema/upload/uploadExperimentPostSchema.ts
Labels: refactor, design

#73 [YS-334] 회원 탈퇴 UI 퍼블리싱 및 회원 탈퇴 기능 구현 & 로그아웃 구현
  src/apis/login.ts
  src/apis/user.ts
  src/app/home/hooks/useUserInfo.ts
  src/app/join/components/JoinInput/JoinInput.tsx
  src/app/join/components/Participant/ParticipantForm.tsx
  src/app/join/components/Researcher/ResearcherForm.tsx
  src/app/join/hooks/useServiceAgreeCheck.ts
  src/app/join/page.tsx
  src/app/login/LoginPage.css.ts
  src/app/login/page.tsx
  src/app/user/leave/LeavePage.css.ts
  src/app/user/leave/layout.tsx
  src/app/user/leave/page.tsx
  src/app/user/profile/components/ParticipantUserInfo/ParticipantUserInfo.tsx
  src/app/user/profile/components/ResearcherUserInfo/ResearcherUserInfo.tsx
  src/app/user/profile/hooks/useFormParticipantUserInfo.ts
  src/app/user/profile/hooks/useFormResearcherUserInfo.tsx
  src/app/user/success/layout.tsx
  src/app/user/success/page.tsx
  src/app/user/success/success.css.ts
  src/components/Header/Header.css.ts
  src/components/Header/Header.tsx
  src/components/Header/Menu.css.ts
  src/components/Header/Menu.tsx
  src/constants/url.ts
  src/hooks/useSessionStorage.ts
  src/schema/profile/LeaveSchema.ts
  src/schema/profile/ParticipantUpdateSchema.ts
  src/schema/profile/ResearcherUpdateSchema.ts
Labels: feat

#76 [YS-351] QA 반영 및 약관 동의 문구 추가
  package.json
  pnpm-lock.yaml
  src/apis/login.ts
  src/app/home/components/Banner/Banner.css.ts
  src/app/home/components/Banner/Banner.tsx
  src/app/home/components/ExperimentPostContainer/ExperimentPostCardListContainer/ExperimentPostCardList/ExperimentPostCard/ExperimentPostCard.tsx
  src/app/join/JoinPage.constants.ts
  src/app/join/JoinPage.utils.ts
  src/app/join/components/JoinCheckboxContainer/AgreeAccordion/AgreeAccordion.css.ts
  src/app/join/components/JoinCheckboxContainer/AgreeAccordion/AgreeAccordion.tsx
  src/app/join/components/JoinCheckboxContainer/JoinCheckbox/JoinCheckbox.css.ts
  src/app/join/components/JoinCheckboxContainer/JoinCheckboxContainer.css.ts
  src/app/join/components/JoinCheckboxContainer/JoinCheckboxContainer.tsx
  src/app/join/components/JoinCheckboxContainer/Policy.tsx
  src/app/join/components/Participant/JoinEmailStep/JoinEmailStep.tsx
  src/app/join/components/Participant/ParticipantForm.tsx
  src/app/join/components/Researcher/JoinEmailStep/JoinEmailStep.tsx
  src/app/join/components/Researcher/ResearcherForm.tsx
  src/app/join/hooks/useCheckValidEmailInfoQuery.ts
  src/app/join/hooks/useServiceAgreeCheck.ts
  src/app/join/page.tsx
  src/app/login/components/LoginCard/LoginCard.tsx
  src/app/login/google/page.tsx
  src/app/login/hooks/useNaverLoginMutation.ts
  src/app/login/naver/page.tsx
  src/app/user/profile/components/ButtonInput/ButtonInput.tsx
  src/app/user/profile/components/ParticipantUserInfo/ParticipantUserInfo.tsx
  src/app/user/profile/components/ResearcherUserInfo/ResearcherUserInfo.tsx
  src/assets/images/banner.webp
  src/constants/queryKey.ts
  src/constants/url.ts
  src/schema/join/ParticipantJoinSchema.ts
  src/schema/join/ResearcherJoinSchema.ts
  src/types/post.ts
Labels: fix, refactor
