Repository YAPP-Github/25th-Web-Team-2-FE, pull requests merged in 2025-04, with the labels that each got.

#92 [YS-408] 필터링 초기화 시 저장 버튼 활성화가 안됨
  src/apis/post.ts
  src/app/home/components/ExperimentPostContainer/FilterContainer/AreaFilter/AreaFilter.css.ts
  src/app/home/components/ExperimentPostContainer/FilterContainer/AreaFilter/AreaFilter.tsx
  src/app/home/components/ExperimentPostContainer/FilterContainer/AreaFilter/components/AreaContainer/AreaContainer.css.ts
  src/app/home/components/ExperimentPostContainer/FilterContainer/AreaFilter/components/AreaContainer/AreaContainer.tsx
  src/app/home/components/ExperimentPostContainer/FilterContainer/AreaFilter/components/FooterButtonContainer/FooterButtonContainer.css.ts
  src/app/home/components/ExperimentPostContainer/FilterContainer/AreaFilter/components/FooterButtonContainer/FooterButtonContainer.tsx
  src/app/home/components/ExperimentPostContainer/FilterContainer/AreaFilter/components/RegionContainer/RegionContainer.css.ts
  src/app/home/components/ExperimentPostContainer/FilterContainer/AreaFilter/components/RegionContainer/RegionContainer.tsx
  src/app/home/components/ExperimentPostContainer/FilterContainer/AreaFilter/hooks/useAreaFilter.ts
  src/app/home/home.constants.ts
  src/app/home/home.utils.ts
  src/app/home/hooks/usePostAreaCountQuery.ts
Labels: fix

#96 [YS-412] nextjs 보안 취약점 발견으로 인한 패키지 업데이트
  package.json
  pnpm-lock.yaml
Labels: fix

#100 [YS-414] 에러 코드 정의 및 에러 핸들링 로직 개선
  src/apis/config.ts
  src/apis/config/constants.ts
  src/apis/config/index.ts
  src/apis/config/types.ts
  src/apis/config/utils.ts
  src/apis/type.ts
Labels: refactor

#103 [YS-416] 내 정보 수정 QA 반영 + 회원탈퇴 QA 반영 및 리팩토링
  src/app/user/leave/LeavePage.css.ts
  src/app/user/leave/components/LeaveAgreeCheckContainer/LeaveAgreeCheckContainer.css.ts
  src/app/user/leave/components/LeaveAgreeCheckContainer/LeaveAgreeCheckContainer.tsx
  src/app/user/leave/components/LeaveButtonContainer/LeaveButtonContainer.css.ts
  src/app/user/leave/components/LeaveButtonContainer/LeaveButtonContainer.tsx
  src/app/user/leave/components/LeaveHeader/LeaveHeader.css.ts
  src/app/user/leave/components/LeaveHeader/LeaveHeader.tsx
  src/app/user/leave/components/LeaveMessageContainer/LeaveMessageContainer.css.ts
  src/app/user/leave/components/LeaveMessageContainer/LeaveMessageContainer.tsx
  src/app/user/leave/components/LeaveReasonForm/LeaveReasonForm.css.ts
  src/app/user/leave/components/LeaveReasonForm/LeaveReasonForm.tsx
  src/app/user/leave/hooks/useLeaveForm.ts
  src/app/user/leave/hooks/useLeaveMutation.ts
  src/app/user/leave/page.tsx
  src/app/user/profile/hooks/useFormResearcherUserInfo.tsx
  src/components/Header/Header.css.ts
  src/components/Header/Menu.css.ts
  src/components/Header/RightHeader/RightHeader.tsx
  src/schema/profile/LeaveSchema.ts
Labels: fix, refactor

#104 [YS-409] 회원가입 로직 QA 반영
  src/apis/config/error.ts
  src/apis/config/index.ts
  src/apis/config/utils.ts
  src/apis/login.ts
  src/app/join/components/JoinInput/JoinInput.tsx
  src/app/join/components/Participant/JoinEmailStep/JoinEmailStep.tsx
  src/app/join/components/Participant/JoinInfoStep/JoinInfoStep.tsx
  src/app/join/components/Researcher/JoinEmailStep/JoinEmailStep.tsx
  src/app/join/components/Researcher/JoinEmailStep/UnivAuthInput/UnivAuthInput.css.ts
  src/app/join/components/Researcher/JoinEmailStep/UnivAuthInput/UnivAuthInput.tsx
  src/app/join/hooks/useSendUnivAuthCodeMutation.ts
  src/app/join/hooks/useVerifyUnivEmail.ts
  src/app/user/profile/components/ParticipantUserInfo/ParticipantUserInfo.tsx
  src/app/user/profile/components/ResearcherUserInfo/ResearcherUserInfo.tsx
  src/components/ButtonInput/ButtonInput.css.ts
  src/components/ButtonInput/ButtonInput.tsx
  src/styles/reset.css.ts
Labels: fix

#107 [YS-420] 로그인 후 재요청 실패 시 에러 처리 추가 및 에러 코드별 alertModal 처리
  src/apis/config/index.ts
  src/app/edit/[post_id]/components/EditExperimentPost.tsx
  src/app/edit/[post_id]/hooks/useOriginExperimentPostQuery.ts
  src/app/home/components/ExperimentPostContainer/ExperimentPostCardListContainer/ExperimentPostCardListContainer.tsx
  src/app/home/components/ExperimentPostContainer/ExperimentPostContainer.css.ts
  src/app/my-posts/components/MyPostsTable/MyPostsTable.tsx
  src/app/post/[post_id]/components/ExperimentPostContainer/ExperimentPostContainer.tsx
  src/app/post/[post_id]/hooks/useApplyMethodQuery.ts
  src/app/upload/components/UploadContainer/UploadContainer.tsx
  src/app/upload/hooks/useManageExperimentPostForm.tsx
  src/components/Header/Header.css.ts
  src/components/Modal/AlertModal/AlertModal.tsx
  src/components/layout/DefaultLayout/DefaultLayout.css.ts
  src/lib/mixpanelClient.ts
Labels: refactor

#112 [YS-424] 회원가입 중간에 페이지를 이동할 경우 무한 로딩되는 오류 해결
  .cursor/rules/frontend-fundamental.mdc
  src/apis/config/error.ts
  src/apis/config/index.ts
  src/apis/config/utils.ts
  src/app/home/hooks/useParticipantInfoQuery.ts
  src/app/home/hooks/useResearcherInfoQuery.ts
Labels: fix

#123 [YS-374] 밀린 디자인 화면 반영 및 QA 수정
  src/app/my-posts/MyPostsPage.css.ts
  src/app/my-posts/components/MyPostsContainer/MyPostsContainer.tsx
  src/app/my-posts/components/MyPostsHeader/MyPostHeader.tsx
  src/app/my-posts/components/MyPostsHeader/MyPostsHeader.css.ts
  src/app/my-posts/components/MyPostsTable/MyPostsTable.css.ts
  src/app/my-posts/components/MyPostsTable/MyPostsTable.tsx
  src/app/my-posts/components/Pagination/Pagination.css.ts
  src/app/my-posts/components/PostActionsPopover/PostActionsPopover.css.ts
  src/app/my-posts/components/PostActionsPopover/PostActionsPopover.tsx
  src/app/upload/components/DatePickerForm/DatePickerForm.css.ts
  src/app/upload/components/DatePickerForm/DatePickerForm.tsx
  src/app/upload/components/DescriptionSection/DescriptionSection.tsx
  src/app/upload/components/InputForm/InputForm.css.ts
  src/app/upload/components/OutlineSection/OutlineSection.css.ts
  src/components/Icon/icons/MenuDots.tsx
  src/components/Icon/icons/ToggleOff.tsx
  src/components/Icon/icons/ToggleOn.tsx
Labels: design

#125 [RELEASE] 1.1.2
  src/apis/config/constants.ts
  src/apis/config/index.ts
  src/apis/config/utils.ts
  src/apis/login.ts
  src/apis/user.ts
  src/app/CustomQueryClientProvider.tsx
  src/app/home/components/ExperimentPostContainer/ExperimentPostCardListContainer/ExperimentPostCardList/ExperimentPostCard/ExperimentPostCard.css.ts
  src/app/home/components/ExperimentPostContainer/ExperimentPostCardListContainer/ExperimentPostCardListContainer.tsx
  src/app/home/components/ExperimentPostContainer/ExperimentPostContainer.tsx
  src/app/home/home.types.ts
  src/app/home/home.utils.ts
  src/app/home/hooks/useExperimentFilters.ts
  src/app/home/hooks/useUserInfo.ts
  src/app/join/JoinPage.css.ts
  src/app/join/components/JoinSuccessStep/JoinSuccessStep.css.ts
  src/app/join/components/JoinSuccessStep/JoinSuccessStep.tsx
  src/app/join/components/Participant/JoinInfoStep/JoinInfoStep.css.ts
  src/app/join/components/Participant/JoinInfoStep/JoinInfoStep.tsx
  src/app/join/components/Researcher/JoinEmailStep/JoinEmailStep.css.ts
  src/app/join/components/Researcher/JoinEmailStep/JoinEmailStep.tsx
  src/app/join/components/Researcher/JoinEmailStep/UnivAuthInput/UnivAuthInput.tsx
  src/app/join/components/Researcher/JoinInfoStep/JoinInfoStep.tsx
  src/app/layout.tsx
  src/app/login/LoginPage.css.ts
  src/app/login/LoginPage.utils.ts
  src/app/login/components/LoginCard/LoginCard.tsx
  src/app/login/hooks/useGoogleLoginMutation.ts
  src/app/login/hooks/useNaverLoginMutation.ts
  src/app/login/page.tsx
  src/app/my-posts/MyPostsPage.css.ts
  src/app/my-posts/components/MyPostsContainer/MyPostsContainer.tsx
  src/app/my-posts/components/MyPostsHeader/MyPostHeader.tsx
  src/app/my-posts/components/MyPostsHeader/MyPostsHeader.css.ts
  src/app/my-posts/components/MyPostsTable/MyPostsTable.css.ts
  src/app/my-posts/components/MyPostsTable/MyPostsTable.tsx
  src/app/my-posts/components/Pagination/Pagination.css.ts
  src/app/my-posts/components/PostActionsPopover/PostActionsPopover.css.ts
  src/app/my-posts/components/PostActionsPopover/PostActionsPopover.tsx
  src/app/providers.tsx
  src/app/upload/components/DatePickerForm/DatePickerForm.css.ts
  src/app/upload/components/DatePickerForm/DatePickerForm.tsx
  src/app/upload/components/DescriptionSection/DescriptionSection.tsx
  src/app/upload/components/InputForm/InputForm.css.ts
  src/app/upload/components/OutlineSection/OutlineSection.css.ts
  src/app/upload/hooks/useUserResearcherInfo.ts
  src/app/user/leave/components/LeaveHeader/LeaveHeader.css.ts
  src/app/user/leave/components/LeaveHeader/LeaveHeader.tsx
  src/app/user/leave/hooks/useLeaveForm.ts
  src/components/ButtonInput/ButtonInput.tsx
  src/components/Icon/icons/MenuDots.tsx
  src/components/Icon/icons/ToggleOff.tsx
  src/components/Icon/icons/ToggleOn.tsx
  src/constants/config.ts
  src/schema/profile/LeaveSchema.ts
  src/types/user.ts
Labels: deploy
