Repository YAPP-Github/25th-Web-Team-2-FE, pull requests merged in 2025-01, with the labels that each got.

#4 [FEAT] 공통 레이아웃 설정
  package.json
  pnpm-lock.yaml
  src/app/page.tsx
  src/assets/images/logo.svg
  src/components/Footer/Footer.styles.ts
  src/components/Footer/Footer.tsx
  src/components/Header/Header.styles.ts
  src/components/Header/Header.tsx
  src/components/layout/DefaultLayout.tsx
Labels: feat

#7 [YS-86] 공고 조회 화면 UI 퍼블리싱
  package.json
  pnpm-lock.yaml
  src/app/layout.tsx
  src/app/page.tsx
  src/app/post/[post_id]/PostPage.styles.ts
  src/app/post/[post_id]/PostPage.types.ts
  src/app/post/[post_id]/PostPage.utils.ts
  src/app/post/[post_id]/components/DeleteConfirmModal/DeleteConfirmModal.styles.ts
  src/app/post/[post_id]/components/DeleteConfirmModal/DeleteConfirmModal.tsx
  src/app/post/[post_id]/components/ParticipationGuideModal/ParticipationGuideModal.styles.ts
  src/app/post/[post_id]/components/ParticipationGuideModal/ParticipationGuideModal.tsx
  src/app/post/[post_id]/components/PostContainer/PostContainer.styles.ts
  src/app/post/[post_id]/components/PostContainer/PostContainer.tsx
  src/app/post/[post_id]/components/PostDetailContent/PostDetailContent.styles.ts
  src/app/post/[post_id]/components/PostDetailContent/PostDetailContent.tsx
  src/app/post/[post_id]/components/PostInfo/PostInfo.styles.ts
  src/app/post/[post_id]/components/PostInfo/PostInfo.tsx
  src/app/post/[post_id]/components/PostOutline/PostOutline.styles.ts
  src/app/post/[post_id]/components/PostOutline/PostOutline.tsx
  src/app/post/[post_id]/layout.tsx
  src/app/post/[post_id]/page.tsx
  src/components/Button/BackToTopButton/BackToTopButton.styles.ts
  src/components/Button/BackToTopButton/BactToTopButton.tsx
  src/components/Footer/Footer.styles.ts
  src/components/Header/Header.styles.ts
  src/components/Header/Header.tsx
  src/components/Icon/icons/Alert.tsx
  src/components/Icon/icons/BackToTopGroup.tsx
  src/components/Icon/icons/Calendar.tsx
  src/components/Icon/icons/ChevronSquare.tsx
  src/components/Icon/icons/Copy.tsx
  src/components/Icon/icons/Information.tsx
  src/components/Icon/icons/Maximize.tsx
  src/components/Icon/icons/Minimize.tsx
  src/components/Icon/icons/X.tsx
  src/components/Icon/icons/index.ts
  src/components/Icon/index.tsx
  src/components/layout/DefaultLayout.tsx
  src/components/layout/DefaultLayout/DefaultLayout.styles.ts
  src/components/layout/DefaultLayout/DefaultLayout.tsx
  src/styles/fonts.ts
  src/styles/global.ts
  src/styles/theme.ts
  src/styles/zIndex.ts
Labels: feat, design

#8 [YS-85] 홈 화면 퍼블리싱 및 msw 연동
  package.json
  pnpm-lock.yaml
  src/apis/config.ts
  src/apis/post.ts
  src/app/home/components/Banner/Banner.styles.ts
  src/app/home/components/Banner/Banner.tsx
  src/app/home/components/PostCard/PostCard.styles.ts
  src/app/home/components/PostCard/PostCard.tsx
  src/app/home/components/PostCardList/PostCardList.styles.ts
  src/app/home/components/PostCardList/PostCardList.tsx
  src/app/home/components/PostContainer/AreaFilter/AreaFilter.styles.ts
  src/app/home/components/PostContainer/AreaFilter/AreaFilter.tsx
  src/app/home/components/PostContainer/ContactTargetPopover/ContactTargetFilter.styles.ts
  src/app/home/components/PostContainer/ContactTargetPopover/ContactTargetFilter.tsx
  src/app/home/components/PostContainer/FilterContainer/FilterContainer.styles.ts
  src/app/home/components/PostContainer/FilterContainer/FilterContainer.tsx
  src/app/home/components/PostContainer/PostContainer.styles.ts
  src/app/home/components/PostContainer/PostContainer.tsx
  src/app/home/components/PostContainer/ProgressMethodFilter/ProgressMethodFilter.styles.ts
  src/app/home/components/PostContainer/ProgressMethodFilter/ProgressMethodFilter.tsx
  src/app/home/home.constants.ts
  src/app/home/home.types.ts
  src/app/home/hooks/useFilterAreaQuery.ts
  src/app/home/hooks/useFilterSubAreaQuery.ts
  src/app/home/hooks/usePostListQuery.ts
  src/app/page.tsx
  src/assets/images/banner.svg
  src/components/Footer/Footer.styles.ts
  src/components/Header/Header.tsx
  src/components/Icon/icons/BackToTopGroup.tsx
  src/components/layout/DefaultLayout/DefaultLayout.styles.ts
  src/constants/queryKey.ts
  src/constants/url.ts
  src/mocks/data/postArea.json
  src/mocks/data/postList.json
  src/mocks/data/postSubArea.json
  src/mocks/data/test.json
  src/mocks/handlers/index.ts
  src/mocks/handlers/postHandler.ts
  src/styles/reset.ts
  src/types/post.ts
Labels: feat, design

#11 [YS-137] next/local/font 폰트 적용
  public/fonts/Pretendard-Bold.subset.woff2
  public/fonts/Pretendard-Medium.subset.woff2
  public/fonts/Pretendard-Regular.subset.woff2
  public/fonts/Pretendard-SemiBold.subset.woff2
  src/app/layout.tsx
  src/fonts/local-font.ts
  src/styles/global.ts
Labels: feat

#13 [YS-135] 로그인 UI 퍼블리싱 및 구글 OAuth 로그인 연동
  src/apis/config.ts
  src/apis/login.ts
  src/apis/post.ts
  src/app/home/components/Banner/Banner.tsx
  src/app/home/components/PostCard/PostCard.tsx
  src/app/home/components/PostCardList/PostCardList.tsx
  src/app/home/components/PostContainer/AreaFilter/AreaFilter.tsx
  src/app/home/components/PostContainer/ContactTargetPopover/ContactTargetFilter.tsx
  src/app/home/components/PostContainer/FilterContainer/FilterContainer.tsx
  src/app/home/components/PostContainer/ProgressMethodFilter/ProgressMethodFilter.tsx
  src/app/home/hooks/useFilterAreaQuery.ts
  src/app/home/hooks/useFilterSubAreaQuery.ts
  src/app/home/hooks/usePostListQuery.ts
  src/app/join/page.tsx
  src/app/login/LoginPage.styles.ts
  src/app/login/components/LoginCard.styles.ts
  src/app/login/components/LoginCard.tsx
  src/app/login/google/GoogleLoginPage.styles.ts
  src/app/login/google/page.tsx
  src/app/login/hooks/useGoogleLoginMutation.ts
  src/app/login/layout.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/assets/images/google.svg
  src/assets/images/naver.svg
  src/components/Header/Header.styles.ts
  src/components/Header/Header.tsx
  src/components/layout/DefaultLayout/DefaultLayout.styles.ts
  src/constants/url.ts
  src/mocks/handlers/postHandler.ts
  src/styles/global.ts
  src/styles/reset.ts
Labels: feat, design

#17 [YS-162] 공고 등록 시 사진 추가 구현
  src/app/upload/components/DescriptionSection/DescriptionSection.tsx
  src/components/Icon/icons/CloseRound.tsx
Labels: feat

#23 [YS-176] 회원가입 로직 리팩토링 (연구자)
  src/apis/login.ts
  src/apis/post.ts
  src/app/home/components/PostCard/PostCard.tsx
  src/app/home/components/PostContainer/PostContainer.tsx
  src/app/home/hooks/usePostListQuery.ts
  src/app/home/hooks/useResearcherInfoQuery.ts
  src/app/join/JoinEmailStep.tsx
  src/app/join/JoinInfoStep.tsx
  src/app/join/JoinPage.styles.ts
  src/app/join/JoinPage.types.ts
  src/app/join/JoinPage.utils.ts
  src/app/join/JoinSuccessStep.tsx
  src/app/join/components/JoinCheckboxContainer/JoinCheckboxContainer.tsx
  src/app/join/components/JoinEmailStep/JoinCheckboxContainer/JoinCheckbox/JoinCheckbox.styles.ts
  src/app/join/components/JoinEmailStep/JoinCheckboxContainer/JoinCheckbox/JoinCheckbox.tsx
  src/app/join/components/JoinEmailStep/JoinCheckboxContainer/JoinCheckboxContainer.styles.ts
  src/app/join/components/JoinEmailStep/JoinCheckboxContainer/JoinCheckboxContainer.tsx
  src/app/join/components/JoinEmailStep/JoinEmailStep.styles.ts
  src/app/join/components/JoinEmailStep/JoinEmailStep.tsx
  src/app/join/components/JoinEmailStep/UnivAuthInput/AuthCodeInput/AuthCodeInput.styles.ts
  src/app/join/components/JoinEmailStep/UnivAuthInput/AuthCodeInput/AuthCodeInput.tsx
  src/app/join/components/JoinEmailStep/UnivAuthInput/UnivAuthInput.styles.ts
  src/app/join/components/JoinEmailStep/UnivAuthInput/UnivAuthInput.tsx
  src/app/join/components/JoinInfoStep/JoinInfoStep.styles.ts
  src/app/join/components/JoinInfoStep/JoinInfoStep.tsx
  src/app/join/components/JoinInput/JoinInput.styles.ts
  src/app/join/components/JoinInput/JoinInput.tsx
  src/app/join/components/JoinSuccessStep/JoinSuccessStep.styles.ts
  src/app/join/components/JoinSuccessStep/JoinSuccessStep.tsx
  src/app/join/components/UnivAuthInput/AuthCodeInput/AuthCodeInput.tsx
  src/app/join/hooks/useAuthCodeTimer.ts
  src/app/join/hooks/useFunnel.tsx
  src/app/join/hooks/useJoinMutation.ts
  src/app/join/hooks/useSendUnivAuthCodeMutation.ts
  src/app/join/hooks/useServiceAgreeCheck.ts
  src/app/join/hooks/useVerifyUnivAuthCodeMutation.ts
  src/app/join/layout.tsx
  src/app/join/page.tsx
  src/app/login/components/LoginCard.tsx
  src/app/login/hooks/useNaverLoginMutation.ts
  src/app/login/naver/NaverLoginPage.styles.ts
  src/app/login/naver/page.tsx
  src/app/upload/components/RegionPopover/RegionPopover.tsx
  src/components/Header/Header.tsx
  src/constants/url.ts
  src/styles/fonts.ts
  src/types/post.ts
Labels: refactor

#26 [YS-172] 공고 등록 react-hook-form 유효성 검증 및 공고 등록 구현
  package.json
  pnpm-lock.yaml
  src/apis/hooks/useUploadExperimentPostAPI.ts
  src/app/upload/components/AgeForm/AgeForm.styles.ts
  src/app/upload/components/AgeForm/AgeForm.tsx
  src/app/upload/components/ApplyMethodSection/ApplyMethodSection.styles.ts
  src/app/upload/components/ApplyMethodSection/ApplyMethodSection.tsx
  src/app/upload/components/CheckboxWithIcon/CheckboxWithIcon.styles.ts
  src/app/upload/components/CheckboxWithIcon/CheckboxWithIcon.tsx
  src/app/upload/components/CountSelect/CountSelect.tsx
  src/app/upload/components/DatePickerField/DatePickerField.tsx
  src/app/upload/components/DatePickerForm/DatePickerForm.styles.ts
  src/app/upload/components/DatePickerForm/DatePickerForm.tsx
  src/app/upload/components/DescriptionSection/DescriptionSection.styles.ts
  src/app/upload/components/DescriptionSection/DescriptionSection.tsx
  src/app/upload/components/DurationSelect/DurationSelect.tsx
  src/app/upload/components/InputForm/InputForm.styles.ts
  src/app/upload/components/InputForm/InputForm.tsx
  src/app/upload/components/OutlineSection/OutlineSection.styles.ts
  src/app/upload/components/OutlineSection/OutlineSection.tsx
  src/app/upload/components/RadioButtonGroup/RadioButtonGroup.styles.ts
  src/app/upload/components/RadioButtonGroup/RadioButtonGroup.tsx
  src/app/upload/components/RegionPopover/RegionPopover.styles.ts
  src/app/upload/components/RegionPopover/RegionPopover.tsx
  src/app/upload/components/SelectForm/SelectForm.styles.ts
  src/app/upload/components/SelectForm/SelectForm.tsx
  src/app/upload/components/SelectInput/SelectInput.tsx
  src/app/upload/components/TextInput/TextInput.tsx
  src/app/upload/components/UploadContainer/UploadContainer.styles.ts
  src/app/upload/components/UploadContainer/UploadContainer.tsx
  src/app/upload/hooks/useUploadExperimentPost.tsx
  src/app/upload/upload.constants.ts
  src/app/upload/upload.utils.ts
  src/constants/url.ts
  src/schema/upload/uploadExperimentPostSchema.ts
  src/styles/reset.ts
  src/types/uploadExperimentPost.ts
Labels: feat, refactor

#29 [YS-208] 상세 공고 조회 및 참여 방법 조회 API 연동
  src/app/post/[post_id]/PostPage.utils.ts
  src/app/post/[post_id]/components/ParticipationGuideModal/ParticipationGuideModal.tsx
  src/app/post/[post_id]/components/PostContainer/PostContainer.tsx
  src/app/post/[post_id]/components/PostDetailContent/PostDetailContent.tsx
  src/app/post/[post_id]/components/PostInfo/PostInfo.tsx
  src/app/post/[post_id]/components/PostOutline/PostOutline.styles.ts
  src/app/post/[post_id]/components/PostOutline/PostOutline.tsx
  src/app/post/[post_id]/hooks/useApplyMethodQuery.ts
  src/app/post/[post_id]/hooks/useExperimentDetailsQuery.ts
  src/app/upload/components/InputForm/InputForm.tsx
  src/app/upload/components/RadioButtonGroup/RadioButtonGroup.styles.ts
  src/app/upload/components/RegionPopover/RegionPopover.styles.ts
  src/app/upload/components/RegionPopover/RegionPopover.tsx
  src/app/upload/components/SelectForm/SelectForm.styles.ts
  src/app/upload/components/SelectForm/SelectForm.tsx
  src/app/upload/components/UploadContainer/UploadContainer.tsx
  src/app/upload/hooks/useManageExperimentPostForm.tsx
  src/app/upload/hooks/useUploadExperimentPostMutation.ts
  src/app/upload/upload.utils.ts
  src/constants/url.ts
  src/schema/upload/uploadExperimentPostSchema.ts
  src/styles/reset.ts
Labels: feat

#32 [YS-226] emotion -> vanilla extract 마이그레이션 세팅
  next.config.mjs
  package.json
  pnpm-lock.yaml
  src/app/example/example.css.ts
  src/app/example/page.tsx
  src/app/post/[post_id]/components/DeleteConfirmModal/DeleteConfirmModal.css.ts
  src/app/post/[post_id]/components/DeleteConfirmModal/DeleteConfirmModal.styles.ts
  src/app/post/[post_id]/components/DeleteConfirmModal/DeleteConfirmModal.tsx
  src/styles/fonts.css.ts
Labels: feat, chore
