Repository YAPP-Github/25th-Web-Team-2-FE, pull requests merged in 2025-06, with the labels that each got.

#141 [YS-449] design: 공고 상세 불필요한 height 제거 및 flex 추가
  src/app/post/[post_id]/components/ExperimentPostInfo/ExperimentPostInfo.css.ts
  src/app/post/[post_id]/components/ExperimentPostInfo/ExperimentPostInfo.tsx
Labels: fix, deploy

#154 [YS-455] vitest 테스트 환경 도입 & 유틸함수 테스트 코드 작성 & 테스트 코드 PR Comment workflow 추가
  .github/workflows/ci.yml
  package.json
  pnpm-lock.yaml
  src/app/home/components/ExperimentPostContainer/FilterContainer/MatchTypeFilter/MatchTypeFilter.test.tsx
  src/app/home/home.utils.test.ts
  src/app/home/home.utils.ts
  src/tests/setup.ts
  src/tests/test-utils.tsx
  vitest.config.ts
Labels: refactor

#156 [YS-460] 로그인 API에 redirect uri를 보내 개발 서버에서도 구글 OAuth 로그인 적용
  src/apis/login.ts
  src/app/login/hooks/useGoogleLoginMutation.ts
Labels: feat

#173 [YS-477] 모바일 준비중 모달 하루동안 안보기 기능 추가
  src/app/post/[postId]/mobile/ExperimentPostPage.constants.ts
  src/app/post/[postId]/mobile/components/EditNotReadyModal/EditNotReadyModal.css.ts
  src/app/post/[postId]/mobile/components/EditNotReadyModal/EditNotReadyModal.tsx
  src/app/post/[postId]/mobile/components/ExperimentPostMobileContainer/ExperimentPostMobileContainer.tsx
  src/app/post/[postId]/mobile/components/ExperimentPostMobileContentContainer/ExperimentPostMobileContentContainer.tsx
  src/app/post/[postId]/mobile/components/HeaderMenuNotReadyModal/HeaderMenuNotReadyModal.tsx
  src/app/post/[postId]/mobile/components/ParticipationGuideBottomSheet/ParticipationGuideBottomSheet.css.ts
  src/components/Header/RightHeader/components/MobileLoginHeader/MobileLoginHeader.tsx
  src/lib/cookies.ts
Labels: feat

#175 [YS-486] 연구자 회원가입 테스트 코드 고도화
  src/app/join/components/JoinCheckboxContainer/JoinCheckbox/JoinCheckbox.tsx
  src/app/join/components/JoinCheckboxContainer/JoinCheckboxContainer.test.tsx
  src/app/join/components/JoinInput/JoinInput.tsx
  src/app/join/desktop/Researcher/JoinEmailStep/NextButton/NextButton.test.tsx
  src/app/join/desktop/Researcher/JoinEmailStep/UnivAuthInput/AuthCodeInput/AuthCodeInput.test.tsx
  src/app/join/desktop/Researcher/JoinEmailStep/UnivAuthInput/UnivAuthInput.test.tsx
  src/components/ButtonInput/ButtonInput.tsx
  src/lib/mixpanelClient.ts
  src/tests/test-utils.tsx
Labels: refactor

#176 [YS-480] 모바일 헤더의 프로필 아이콘 클릭 시 유저 관련 바텀시트 추가
  src/app/post/[postId]/mobile/ExperimentPostPage.constants.ts
  src/app/post/[postId]/mobile/components/EditNotReadyModal/EditNotReadyModal.tsx
  src/app/post/[postId]/mobile/components/HeaderMenuNotReadyModal/HeaderMenuNotReadyModal.tsx
  src/components/Header/RightHeader/components/MobileLoginHeader/MobileLoginHeader.tsx
  src/components/Header/RightHeader/components/MobileLoginHeader/MypageBottomSheet/MypageBottomSheet.css.ts
  src/components/Header/RightHeader/components/MobileLoginHeader/MypageBottomSheet/MypageBottomSheet.tsx
Labels: feat
