Repository YAPP-Github/25th-Web-Team-2-FE, pull requests merged in 2025-05, with the labels that each got.

#126 [YS-430] axios 제거 및 fetchClient 도입
  package.json
  pnpm-lock.yaml
  src/apis/config/createBaseFetchClient.ts
  src/apis/config/error.ts
  src/apis/config/fetchClient.ts
  src/apis/config/index.ts
  src/apis/config/types.ts
  src/apis/config/utils.ts
  src/apis/login.ts
  src/apis/post.ts
  src/apis/user.ts
  src/app/edit/[post_id]/components/EditExperimentPost.tsx
  src/app/edit/[post_id]/hooks/useEditExperimentPostMutation.ts
  src/app/edit/[post_id]/hooks/useOriginExperimentPostQuery.ts
  src/app/home/components/ExperimentPostContainer/FilterContainer/AreaFilter/components/AreaContainer/AreaContainer.css.ts
  src/app/home/hooks/useParticipantInfoQuery.ts
  src/app/home/hooks/useResearcherInfoQuery.ts
  src/app/join/components/Researcher/JoinEmailStep/UnivAuthInput/UnivAuthInput.tsx
  src/app/join/hooks/useParticipantJoinMutation.ts
  src/app/join/hooks/useResearcherJoinMutation.ts
  src/app/layout.tsx
  src/app/login/LoginPage.utils.ts
  src/app/login/hooks/useGoogleLoginMutation.ts
  src/app/login/hooks/useNaverLoginMutation.ts
  src/app/my-posts/hooks/useDeleteExperimentPostMutation.ts
  src/app/my-posts/hooks/useMyPostsQuery.ts
  src/app/my-posts/hooks/useUpdateRecruitStatusMutation.ts
  src/app/post/[post_id]/hooks/useApplyMethodQuery.ts
  src/app/post/[post_id]/hooks/useExperimentDetailsQuery.ts
  src/app/upload/hooks/useUploadExperimentPostMutation.ts
  src/app/upload/hooks/useUploadImagesMutation.ts
  src/components/layout/DefaultLayout/DefaultLayout.css.ts
  src/providers/CustomQueryClientProvider.tsx
  src/providers/MSWProvider.tsx
  src/providers/Providers.tsx
Labels: feat, refactor

#129 [YS-437] 관리자 사이트 링크 연동
  src/components/Footer/Footer.css.ts
  src/components/Footer/Footer.tsx
  src/constants/externalUrl.ts
Labels: feat

#130 [RELEASE] 1.1.3
  package.json
  pnpm-lock.yaml
  src/apis/config/createBaseFetchClient.ts
  src/apis/config/error.ts
  src/apis/config/fetchClient.ts
  src/apis/config/index.ts
  src/apis/config/types.ts
  src/apis/config/utils.ts
  src/apis/login.ts
  src/apis/post.ts
  src/apis/user.ts
  src/app/edit/[post_id]/components/EditExperimentPost.tsx
  src/app/edit/[post_id]/hooks/useEditExperimentPostMutation.ts
  src/app/edit/[post_id]/hooks/useOriginExperimentPostQuery.ts
  src/app/home/components/ExperimentPostContainer/FilterContainer/AreaFilter/components/AreaContainer/AreaContainer.css.ts
  src/app/home/hooks/useParticipantInfoQuery.ts
  src/app/home/hooks/useResearcherInfoQuery.ts
  src/app/join/components/Researcher/JoinEmailStep/UnivAuthInput/UnivAuthInput.tsx
  src/app/join/hooks/useParticipantJoinMutation.ts
  src/app/join/hooks/useResearcherJoinMutation.ts
  src/app/layout.tsx
  src/app/login/LoginPage.utils.ts
  src/app/login/hooks/useGoogleLoginMutation.ts
  src/app/login/hooks/useNaverLoginMutation.ts
  src/app/my-posts/hooks/useDeleteExperimentPostMutation.ts
  src/app/my-posts/hooks/useMyPostsQuery.ts
  src/app/my-posts/hooks/useUpdateRecruitStatusMutation.ts
  src/app/post/[post_id]/hooks/useApplyMethodQuery.ts
  src/app/post/[post_id]/hooks/useExperimentDetailsQuery.ts
  src/app/upload/hooks/useUploadExperimentPostMutation.ts
  src/app/upload/hooks/useUploadImagesMutation.ts
  src/components/Footer/Footer.css.ts
  src/components/Footer/Footer.tsx
  src/components/layout/DefaultLayout/DefaultLayout.css.ts
  src/constants/externalUrl.ts
  src/providers/CustomQueryClientProvider.tsx
  src/providers/MSWProvider.tsx
  src/providers/Providers.tsx
Labels: deploy
